name: mac-m1
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      run: |
        printf 'password\npassword\n' | sudo passwd runner
        brew install cloudflared
        sudo cloudflared tunnel --url ssh://localhost:22
